moex/urls.py
from django.urls import path
from . import views

# create your routs

app_name = 'moex'

urlpatterns = [

    path('search_moex/', views.security_search_moex, name='search_moex'),
    path('buy/<int:id>/', views.security_buy, name='buy'),
    path('delete_history/<int:id>/',
         views.delete_history,
         name='delete_history'),
    path('detail2/<int:id>/', views.security_detail, name='detail_old'),
    path('detail/<int:id>/', views.security_detail_vue, name='detail'),
    path('detail-new-old/<secid>/', views.new_security_detail, name='new_detail'),
    path('detail-new/<str:s>/', views.new_security_detail_vue, name='new_detail_vue'),
    path('buy-new/<secid>/', views.new_security_buy, name='new_buy'),
    path('add-new/<secid>/', views.add_new_security_for_staff,
         name='add_new_security_for_staff'),
    path('new_security_history/<secid>/',
         views.get_new_security_history, name='get_new_security_history'),
    path('refresh/<int:id>/', views.refresh_security, name='refresh_security'),
    path('follow/<int:id>/', views.security_follow, name='follow'),
    path('sp/<int:id_p>/<int:id_s>/', views.sp, name='sp'),
    path('security_history/<int:id>/',
         views.get_security_history, name='get_security_history'),
    path('old-list/', views.security_list, name='list-old'),
    path('', views.security_list_vue, name='list'),
]

portfolio/api/urls.py
from django.conf import settings
from rest_framework.routers import DefaultRouter, SimpleRouter
from django.urls import path, include
from portfolio.api.views import PortfolioViewSet, PortfolioInvestHistoryViewSet


if settings.DEBUG:
    router = DefaultRouter()
else:
    router = SimpleRouter()

router.register('portfolios', PortfolioViewSet, basename='investmentportfolio')
# portfolios include 'my-list/' for list portfolios by owner
# portfolios include '{id}/follow/' for follow-unfollow portfolios methods=post
# portfolios include '{id}/like/' for like-unlike portfolios methods=post

router.register('portfolios-invest-history',
                PortfolioInvestHistoryViewSet,
                basename='portfolio-invest-history')
# /api/portfolios/invest-history/{invest-history} methods=[post, delete]

urlpatterns = [
    path('', include(router.urls)),
]

portfolio/urls.py
from django.urls import path, include
from rest_framework import routers
from . import views


# create your routs


#router = routers.DefaultRouter()
#router.register(r'portfolios', views.InvestmentPortfolioViewSet)

app_name = 'portfolio'

urlpatterns = [
    path('sentry-debug/', views.trigger_error, name='trigger_error'),
    path('my_portfolios/', views.my_portfolios, name='my_portfolios'),
    path('create2/', views.portfolio_create, name='create_old'),
    path('create/', views.portfolio_create_vue, name='create'),
    path('add_invest/<int:id>/', views.portfolio_add_invest,
         name='add_invest'),
    path('del_invest/<int:id>/', views.portfolio_del_invest,
         name='del_invest'),
    path('refresh_portfolio/<int:id>/', views.refresh_portfolio,
         name='refresh_portfolio'),
    path('delete_portfolio/<int:id>/', views.delete_portfolio,
         name='delete_portfolio'),
    #path('ranking/', views.portfolio_ranking, name='ranking'),
    path('detail2/<int:id>/', views.portfolio_detail, name='detail_old'),
    path('detail/<int:id>/', views.portfolio_detail_vue, name='detail'),
    #path('like/', views.portfolio_like, name='like'),
    path('follow/<int:id>/', views.portfolio_follow, name='follow'),
    #    path("api/", include(router.urls)),
    path('', views.portfolio_list, name='list'),
]

portfolio/models.py
from django.db import models
from bonds.users.models import User
from django.urls import reverse
from django.core.exceptions import ObjectDoesNotExist
from decimal import Decimal, DivisionByZero
from django.dispatch import receiver
from django.db.models.signals import post_save, post_delete
from moex.models import Security
from moex.utils_valute import get_valute_curse
from . import scripts

# Create your models here.


class InvestmentPortfolio(models.Model):
    owner = models.ForeignKey(User,
                              related_name='portfolios',
                              on_delete=models.CASCADE,)
    title = models.CharField(max_length=50)
    invest_cash = models.DecimalField(max_digits=10, decimal_places=2,
                                      default=0)
    today_cash = models.DecimalField(max_digits=10, decimal_places=2,
                                     default=0)
    previos_today_cash = models.DecimalField(max_digits=10, decimal_places=2,
                                             default=0)
    change_today_cash = models.DecimalField(max_digits=5,
                                            decimal_places=2,
                                            default=0)
    ostatok = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    percent_profit = models.DecimalField(max_digits=5, decimal_places=2,
                                         default=0)
    previos_percent_profit = models.DecimalField(max_digits=5,
                                                 decimal_places=2,
                                                 default=0)
    change_percent_profit = models.DecimalField(max_digits=5, decimal_places=2,
                                                default=0)
    year_percent_profit = models.DecimalField(max_digits=5, decimal_places=2,
                                              default=0)
    previos_year_percent_profit = models.DecimalField(max_digits=5,
                                                      decimal_places=2,
                                                      default=0)
    change_year_percent_profit = models.DecimalField(max_digits=5,
                                                     decimal_places=2,
                                                     default=0)
    private = models.CharField(max_length=20,
                               default='da',
                               choices=[('da', 'deny_all'),
                                        ('af', 'allow_friends'),
                                        ('al', 'allow_login'),
                                        ('aa', 'allow_all')])
    manual = models.BooleanField(default=True)
    description = models.CharField(max_length=250, blank=True)
    strategia = models.CharField(max_length=20, blank=True)
    created = models.DateTimeField(auto_now_add=True, db_index=True)
    users_like = models.ManyToManyField(User,
                                        related_name='portfolio_liked',
                                        blank=True)
    total_likes = models.PositiveIntegerField(db_index=True, default=0,
                                              blank=True)
    users_follows = models.ManyToManyField(User,
                                           related_name='portfolio_followed',
                                           blank=True)
    total_followers = models.PositiveIntegerField(db_index=True, default=0,
                                                  blank=True)

    class Meta:
        ordering = ['id']

    def calc_percent_profit(self):
        try:
            percent_profit = scripts.percent_profit(self.today_cash,
                                                    self.invest_cash)
            self.percent_profit = percent_profit
        except ZeroDivisionError:
            return

    def calc_year_percent_profit(self):
        # выбор записей пополнения и снятия денег
        t = self.portfolio_invests.filter(action__in=['pv', 'vp'])
        # формирование списка инвестиций и снятий денег с датами
        invest = [[i.cash_in_rub * (-1)**(i.action == 'pv'), i.date] for i in t]
        year_percent_profit = scripts.year_percent_profit(
            invest, self.today_cash)
        self.year_percent_profit = year_percent_profit

    def __str__(self):
        return self.title

    def request_user_has_permission(self, request_user, check_owner=True):
        if check_owner and request_user == self.owner:
            return True
        if self.private == 'da':
            return False
        if self.private == 'aa':
            return True
        if self.private == 'al':
            return request_user.is_authenticated
        if self.private == 'af':
            if request_user.is_authenticated:
                return request_user.friends.is_friend(
                    self.owner.friends)
            else:
                return False

    def get_absolute_url(self):
        return reverse('portfolio:detail', args=[self.id])

    def calc_invest_cash_portfolio(self):
        # выбор записей пополнения и снятия денег
        t = self.portfolio_invests.filter(action__in=['pv', 'vp'])
        self.invest_cash = sum([i.cash_in_rub * (-1)**(i.action == 'pv') for i in t])

    def calc_today_cash(self):
        if not self.manual:
            securities = self.securities.all()
            total = sum([i.total_cost_in_rub for i in securities])
            self.today_cash = total + self.ostatok
            self.save(update_fields=['today_cash'])
            return True
        else:
            return False

    def save(self, *args, **kwargs):
        super(InvestmentPortfolio, self).save(*args, **kwargs)

    def refresh_portfolio(self):
        self.calc_today_cash()
        self.calc_invest_cash_portfolio()
        self.calc_percent_profit()
        self.calc_year_percent_profit()
        self.save()
        self.owner.vklad.refresh_vklad()

    def refresh_portfolio_changes(self):
        change_year_percent_profit = (
            Decimal(self.year_percent_profit
                    ) - Decimal(self.previos_year_percent_profit))
        self.previos_year_percent_profit = self.year_percent_profit
        self.change_year_percent_profit = change_year_percent_profit
        change_percent_profit = (
            Decimal(self.percent_profit
                    ) - Decimal(self.previos_percent_profit))
        self.previos_percent_profit = self.percent_profit
        self.change_percent_profit = change_percent_profit
        try:
            change_today_cash = (
                Decimal(self.today_cash) - Decimal(self.previos_today_cash)
            ) / Decimal(self.previos_today_cash) * 100
        except DivisionByZero:
            change_today_cash = 0
        self.previos_today_cash = self.today_cash
        self.change_today_cash = change_today_cash
        self.save()


class PortfolioHistory(models.Model):
    portfolio = models.ForeignKey(InvestmentPortfolio,
                                  on_delete=models.CASCADE)
    date = models.DateField()
    percent_profit = models.DecimalField(max_digits=5,
                                         decimal_places=2, default=0)
    year_percent_profit = models.DecimalField(max_digits=5,
                                              decimal_places=2, default=0)

    class Meta:
        ordering = ['-date']

    def calc_percent_profit(self):
        pass

    def calc_year_percent_profit(self):
        pass


class PortfolioInvestHistory(models.Model):
    portfolio = models.ForeignKey(InvestmentPortfolio,
                                  related_name='portfolio_invests',
                                  on_delete=models.CASCADE)
    date = models.DateField()
    cash = models.DecimalField(max_digits=10,
                               decimal_places=2, default=0)
    cash_in_rub = models.DecimalField(max_digits=10,
                                      decimal_places=2, default=0)
    action = models.CharField(max_length=20,
                              default='vklad_to_portfolio',
                              choices=[('vp', 'Пополнение'),
                                       ('pv', 'Снятие'),
                                       ('tp', 'Доход'),
                                       ('bc', 'Комиссия брокера'),
                                       ('br',
                                        'Частичное погашение облигаций'),
                                       ('tax',
                                        'Налог на доход')])
    # при получении дохода учитыавть НДФЛ
    ndfl = models.DecimalField(max_digits=10,
                               decimal_places=2, default=0)
    # при получении дохода можно выбрать по какой бумаге получен доход
    security = models.ForeignKey('moex.Security',
                                 on_delete=models.SET_NULL,
                                 blank=True,
                                 null=True)
    currency = models.CharField(max_length=20,
                                default='SUR',
                                choices=[('SUR', 'РУБ'),
                                         ('USD', 'USD'),
                                         ('EUR', 'EUR'),
                                         ('GBP', 'GBP'),
                                         ('CNY', 'CNY')],
                                blank=True,
                                null=True)

    class Meta:
        ordering = ['-date', 'cash']

    def add_custom_currеncy_cash(self, withdraw=False):
        # функция добавления наличных в иностранной валюте
        # при withdraw=True - снятие наличных
        try:
            valute = self.portfolio.securities.filter(
                security__security_type__exact='currency'
            ).filter(
                security__name__istartswith=self.currency
            ).get()
            if not withdraw:
                valute.count = valute.count + self.cash - self.ndfl
            else:
                if self.cash > valute.count:

portfolio/forms.py
from django import forms
from .models import InvestmentPortfolio, PortfolioInvestHistory


class PortfolioCreateForm(forms.ModelForm):
    class Meta:
        model = InvestmentPortfolio
        fields = ('title', 'private', 'manual', 'strategia', 'description')


class PortfolioInvestForm(forms.ModelForm):
    cash = forms.DecimalField(max_digits=10, decimal_places=2)
    date = forms.DateField()

    class Meta:
        model = PortfolioInvestHistory
        exclude = ['portfolio', 'cash_in_rub']


class RefreshPortfolio(forms.ModelForm):
    class Meta:
        model = InvestmentPortfolio
        fields = ['today_cash', 'private']

portfolio/templates/portfolio/create.html
{% extends "base.html" %}




{% block content %}
<form action="." method="post" class="col-md-4">
  <div class="form-group">
    <label for="id_title">Название портфеля:</label>
    <input type="text" class="form-control" maxlength="50" required id="id_title" name="title" placeholder="Введите название портфеля...">
  </div>
  <div class="form-group mb-3">
  	<label for="id_private">Приватность:</label>
    <select class="form-control" id="id_private" name="private">
      <option selected value="da">Всем запрещено</option>
      <option value="af">Разрешено друзьям</option>
      <option value="al">Разрешено авторизованным</option>
      <option value="aa">Разрешено всем</option>
    </select>
  </div>
  <div class="form-check mb-2">
    <input class="form-check-input" type="checkbox" name="manual" id="id_manual">
    <label for="id_manual">Ручной ввод балланса</label>
  </div>
  <div class="form-group mb-2">
    <label for="id_strategia">Стратегия:</label>
    <input type="text" class="form-control" name="strategia" maxlength="20" id="id_strategia">
  </div>
  <div class="form-group mb-2">
    <label for="id_description">Описание:</label>
    <textarea type="text" class="form-control" name="description" maxlength="250" id="id_description" rows="3"></textarea>
  </div>
  
  {% csrf_token %}
  <button type="submit" class="btn btn-dark">Создать</button>
</form>

{% endblock content %}

portfolio/templates/portfolio/create_vue.html
{% extends "base_with_vue.html" %}
{% load static %}

{% block content %}
  <div id="app">
    
  </div>
{% endblock content %}

{% block page_vue_scripts %}
    <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
    <script src="{% static 'vue/HTTP.js' %}"></script>
    <script src="{% static 'vue/errors.js' %}"></script>
    <script src="{% static 'vue/portfolio/main_create.js' %}"></script>
{% endblock page_vue_scripts %}

portfolio/templates/portfolio/delete.html
{% extends "base.html" %}




{% block content %}
<div class="container">
  <div class="row">
  	<div class="col-md-6">
    	<p>Вы уверены, что хотите удалить портфель "{{ portfolio.title }}"?</p>
			<form action="." method="post" class="d-flex justify-content-around">
			  {% csrf_token %}
			  <button type="submit" class="btn btn-danger">Удалить</button>
				<a class="btn btn-info" href="{% url 'portfolio:detail' portfolio.id %}">Отменить</a>
			</form>
		</div>
	</div>
</div>

{% endblock content %}

portfolio/templates/portfolio/detail_vue.html
{% extends "base_with_vue.html" %}
{% load static %}

{% block content %}
  <div id="app">
    
  </div>
{% endblock content %}

{% block page_vue_scripts %}
    <!-- <script src="https://unpkg.com/vuex@3.6.2"></script> -->
    <script src="https://cdn.jsdelivr.net/npm/vuex@3.6.2/dist/vuex.min.js"></script>
    <script src="{% static 'vue/HTTP.js' %}"></script>
    <script src="{% static 'vue/errors.js' %}"></script>
    <script src="{% static 'vue/portfolio/store_detail.js' %}"></script>
    <script src="{% static 'vue/portfolio/components_detail.js' %}"></script>
    <script src="{% static 'vue/portfolio/main_detail.js' %}"></script>
{% endblock page_vue_scripts %}

portfolio/templates/portfolio/list.html
{% extends "base.html" %}
{% block content %}
{% load moex_extras %}
<h3 class="mt-3 mb-3">Портфели:</h3>
{% include 'portfolio/portfolio_list_template.html' %}
{% endblock content %}

portfolio/templates/portfolio/my_list.html
{% extends "base.html" %}
{% block content %}
{% load moex_extras %}
<a class="btn btn-dark mt-3 mb-3" href="{% url 'portfolio:create' %}">
			Создать портфель
		</a>
	{% if portfolios %}
		<h3>Мои портфели:</h3>
		{% include 'portfolio/my_portfolios_list_template.html' %}
	{% else %}
		<h2>У вас пока нет портфелей.</h2>
	{% endif %}		

{% endblock content %}

portfolio/templates/portfolio/my_portfolios_list_template.html
{% load moex_extras %}

	        <div class="row">
		          <div class="col-md-2 d-none d-md-block">
		            <p>Наименование</p>
		          </div>
		          <div class="col-md-2 d-none d-md-block">
		            <p>Стратегия</p>
		          </div>
		          <div class="col-md-2 d-none d-md-block">
		            <p>Инвестиции</p>
		          </div>
		          <div class="col-md-2 d-none d-md-block">
		            <p>Текущий баланс</p>
		          </div>
		          <div class="col-md-2 d-none d-md-block">
		            Доходность
		          </div>
		          <div class="col-md-2 d-none d-md-block">
		           Годовая доходность
		          </div>
	        </div>
	    <div class="dropdown-divider d-none d-md-block"></div>
		{% for portfolio in portfolios %}
	                    <div class="row">
	                      <div class="col-md-2 mt-1 mb-1">
	                        <a class="btn btn-secondary btn-sm" href="{{ portfolio.get_absolute_url }}">{{ portfolio.title}}</a>
	                      </div>
	                      <div class="col-md-2 mt-1 mb-1">
	                        <span class="d-md-none">Стратегия: </span>{{ portfolio.strategia }}
	                      </div>
	                      <div class="col-md-2 mt-1 mb-1">
	                        <span class="d-md-none">Инвестиции: </span>{{ portfolio.invest_cash}}
	                      </div>
	                      <div class="col-md-2 mt-1 mb-1">
	                        <span class="d-md-none">Текущий баланс: </span>{{ portfolio.today_cash}}<br class="d-none d-md-inline"><span class="d-md-none d-inline"> </span><span class="{{ portfolio.change_today_cash | return_color_and_fas_bootstrap:True }}"><span class="d-md-none d-inline"></span>({{portfolio.change_today_cash}}%)</span>
	                      </div>
	                      <div class="col-md-2 mt-1 mb-1">
	                        <span class="d-md-none">Доходность: </span><span class="{{ portfolio.percent_profit | return_color_and_fas_bootstrap }}">{{ portfolio.percent_profit }}%</span><br class="d-none d-md-inline"><span class="d-md-none d-inline"> </span><span class="{{ portfolio.change_percent_profit | return_color_and_fas_bootstrap:True }}"><span class="d-md-none d-inline"></span>({{portfolio.change_percent_profit}}%)</span>
	                      </div>
	                      <div class="col-md-2 mt-1 mb-1">
	                       <span class="d-md-none">Годовая доходность: </span><span class="{{ portfolio.year_percent_profit | return_color_and_fas_bootstrap }}">{{ portfolio.year_percent_profit }}%</span><br class="d-none d-md-inline"><span class="d-md-none d-inline"> </span><span class="{{ portfolio.change_year_percent_profit | return_color_and_fas_bootstrap:True }}"><span class="d-md-none d-inline"></span>({{portfolio.change_year_percent_profit}}%)</span>
	                      </div>
	                    </div>
	                <div class="dropdown-divider"></div>
	    {% endfor %}

portfolio/templates/portfolio/portfolio_list_template.html
{% load moex_extras %}

		<div class="row">
		          <div class="col-md-3 d-none d-md-block">
		            <p>Наименование</p>
		          </div>
		          <div class="col-md-3 d-none d-md-block">
		            <p>Владелец</p>
		          </div>
		          <div class="col-md-2 d-none d-md-block">
		            <p>Стратегия</p>
		          </div>
		          <div class="col-md-2 d-none d-md-block">
		            Доходность
		          </div>
		          <div class="col-md-2 d-none d-md-block">
		           Годовая доходность
		          </div>
	        </div>
	    <div class="dropdown-divider d-none d-md-block"></div>
{% with user_id=request.user.id%}
	{% for portfolio in portfolios %}
	                <div class="row">
	                      <div class="col-md-3 mb-1 mt-1">
	                        <a class="btn {% if user_id != portfolio.owner.id %}btn-secondary{% else %}btn-success{% endif %} btn-sm" href="{{ portfolio.get_absolute_url }}">{{ portfolio.title}}</a>
	                      </div>
	                      <div class="col-md-3 mb-1 mt-1">
	                        <span class="d-md-none">Владелец: </span><a class="btn btn-warning btn-sm" href="{{ portfolio.owner.get_absolute_url }}">{{ portfolio.owner}}</a>
	                      </div>
	                      <div class="col-md-2 mb-1 mt-1">
	                        <span class="d-md-none">Стратегия: </span><span>{{ portfolio.strategia }}</span></div>
	                      <div class="col-md-2 mb-1 mt-1">
	                        <span class="d-md-none">Доходность: </span><span class="{{ portfolio.percent_profit | return_color_and_fas_bootstrap }}">{{ portfolio.percent_profit }}%</span><br class="d-none d-md-inline"><span class="d-md-none d-inline"> </span><span class="{{portfolio.change_percent_profit | return_color_and_fas_bootstrap:True }}"><span class="d-md-none d-inline"></span>({{portfolio.change_percent_profit}}%)</span>
	                      </div>
	                      <div class="col-md-2 mb-1 mt-1">
	                       <span class="d-md-none">Годовая доходность: </span><span class="{{ portfolio.year_percent_profit | return_color_and_fas_bootstrap }}">{{ portfolio.year_percent_profit }}%</span><br class="d-none d-md-inline"><span class="d-md-none d-inline"> </span><span class="{{portfolio.change_year_percent_profit | return_color_and_fas_bootstrap:True }}"><span class="d-md-none d-inline"></span>({{portfolio.change_year_percent_profit}}%)</span>
	                      </div>
	                    </div>
	                <div class="dropdown-divider"></div>
    {% endfor %}
{% endwith %}