moex/api/urls.py
from django.conf import settings
from rest_framework.routers import DefaultRouter, SimpleRouter
from django.urls import path, include
from moex.api.views import SecurityViewSet, TradeHistoryViewSet


if settings.DEBUG:
    router = DefaultRouter()
else:
    router = SimpleRouter()

router.register('securities', SecurityViewSet, basename='securities')
router.register('securities-trade-history',
                TradeHistoryViewSet,
                basename='securities-trade-history')
# include delete method
# include create method
# include get method "securities-trade-history/portfolio-list/?portfolio=q
# include get method "securities-trade-history/security-list/?security=q
urlpatterns = [
    path('', include(router.urls)),
]

moex/urls.py
from django.urls import path
from . import views

# create your routs

app_name = 'moex'

urlpatterns = [

    path('search_moex/', views.security_search_moex, name='search_moex'),
    path('buy/<int:id>/', views.security_buy, name='buy'),
    path('delete_history/<int:id>/',
         views.delete_history,
         name='delete_history'),
    path('detail2/<int:id>/', views.security_detail, name='detail_old'),
    path('detail/<int:id>/', views.security_detail_vue, name='detail'),
    path('detail-new-old/<secid>/', views.new_security_detail, name='new_detail'),
    path('detail-new/<str:s>/', views.new_security_detail_vue, name='new_detail_vue'),
    path('buy-new/<secid>/', views.new_security_buy, name='new_buy'),
    path('add-new/<secid>/', views.add_new_security_for_staff,
         name='add_new_security_for_staff'),
    path('new_security_history/<secid>/',
         views.get_new_security_history, name='get_new_security_history'),
    path('refresh/<int:id>/', views.refresh_security, name='refresh_security'),
    path('follow/<int:id>/', views.security_follow, name='follow'),
    path('sp/<int:id_p>/<int:id_s>/', views.sp, name='sp'),
    path('security_history/<int:id>/',
         views.get_security_history, name='get_security_history'),
    path('old-list/', views.security_list, name='list-old'),
    path('', views.security_list_vue, name='list'),
]

moex/models.py
from django.db import models
from decimal import Decimal
#from portfolio.models import InvestmentPortfolio
from django.core.exceptions import ObjectDoesNotExist
from bonds.users.models import User
from django.urls import reverse
from rest_framework.reverse import reverse as api_reverse
# from datetime import datetime
from django.utils.timezone import now
from django.dispatch import receiver
from django.db.models.signals import post_save, post_delete
import threading
import django.dispatch
from .rshb import *
from .iss_simple_main import history as moex_history,\
    specification as moex_specification
from .utils_valute import refresh_valute_curse, get_valute_history
from .utils_yfinance import get_history_by_secid
# Create your models here.

refresh_price_security = django.dispatch.Signal(providing_args=["price"])
# Модель ценных бумаг

currency_choises = [('SUR', 'РУБ'),
                    ('USD', 'USD'),
                    ('EUR', 'EUR'),
                    ('GBP', 'GBP'),
                    ('CNY', 'CNY')]


class Security(models.Model):
    name = models.CharField(max_length=50, unique=True)
    url = models.URLField(blank=True)
    security_type = models.CharField(max_length=20,
                                     default='bond',
                                     choices=[('pif_rshb', 'ОПИФ РСХБ'),
                                              ('ppif', 'БПИФ'),
                                              ('share', 'Акция'),
                                              ('bond', 'Облигация'),
                                              ('futures', 'Фьючерс'),
                                              ('index', 'Индекс'),
                                              ('etf_ppif', 'ETF'),
                                              ('depositary_receipt',
                                               'Депозитарная расписка'),
                                              ('currency', 'Валюта'), ])
    parce_url = models.URLField(blank=True)
    code = models.CharField(max_length=30, blank=True, unique=True, null=True)
    shortname = models.CharField(max_length=50, blank=True, unique=True)
    fullname = models.CharField(max_length=100, blank=True, unique=True)
    regnumber = models.CharField(
        max_length=30, blank=True, unique=True, null=True)
    secid = models.CharField(max_length=30, blank=True, unique=True, null=True)
    isin = models.CharField(max_length=30, blank=True, unique=True, null=True)
    emitent = models.CharField(max_length=250, blank=True)
    board = models.CharField(max_length=250, blank=True)
    engine = models.CharField(max_length=250, blank=True)
    market = models.CharField(max_length=250, blank=True)
    description = models.CharField(max_length=250, blank=True)
    source = models.CharField(max_length=20,
                              default='moex',
                              choices=[('rshb', 'РСХБ'),
                                       ('moex', 'МосБиржа'),
                                       ('yfinance', 'YFinance'),
                                       ('cbr', 'Центробанк')])
    website = models.CharField(max_length=250, blank=True)
    # Номинальная стоимость
    facevalue = models.DecimalField(max_digits=17, decimal_places=7,
                                    blank=True, default=0)
    # объем выпуска
    issuesize = models.DecimalField(max_digits=25, decimal_places=7,
                                    blank=True, default=0)
    # Первоначальная номинальная стоимость
    initialfacevalue = models.DecimalField(max_digits=17, decimal_places=7,
                                           blank=True, default=0)
    # Дата погашения
    matdate = models.DateField(blank=True, null=True)
    # Дата выплаты купона
    coupondate = models.DateField(blank=True, null=True)
    # Периодичность выплаты купона в год
    couponfrequency = models.IntegerField(blank=True, null=True)
    # Ставка купона, %
    couponpercent = models.DecimalField(max_digits=17, decimal_places=7,
                                        blank=True, null=True)
    # НКД для облигаций
    accint = models.DecimalField(max_digits=17, decimal_places=7,
                                 blank=True, null=True)
    # валюта номинала
    faceunit = models.CharField(max_length=20,
                                default='SUR',
                                choices=currency_choises,
                                blank=True,
                                null=True)
    # валюта на основном режиме торгов
    main_board_faceunit = models.CharField(max_length=20,
                                           default='SUR',
                                           choices=currency_choises,
                                           blank=True,
                                           null=True)
    # Сумма купона, в валюте номинала
    couponvalue = models.DecimalField(max_digits=17, decimal_places=7,
                                      blank=True, null=True)
    today_price = models.DecimalField(max_digits=17, decimal_places=7,
                                      default=0)
    last_update = models.DateField(blank=True)
    oldest_date = models.DateField(blank=True)
    created = models.DateTimeField(auto_now_add=True,
                                   db_index=True)
    users_follows = models.ManyToManyField(User,
                                           related_name='security_followed',
                                           blank=True)
    # флаг отслеживания цен при ежедневном обновлении
    monitor = models.BooleanField(default=True)
    # процент изменения цены по сравнению с предыдущим значением
    # (предыдущим днем)
    change_price_percent = models.DecimalField(max_digits=10, decimal_places=3,
                                               default=0)

    class Meta:
        ordering = ['-last_update']

    def get_absolute_url(self):
        return reverse('moex:detail', args=[self.id])

    def get_api_url(self):
        return api_reverse('api:security-detail', args=[self.id])

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        super(Security, self).save(*args, **kwargs)
        # portfolios_for_refresh = self.portfolios.all()
        # for item in portfolios_for_refresh:
        #     item.portfolio.refresh_portfolio()

    def refresh_price(self, first=False, force=False):
        if self.source == 'yfinance':
            if force or self.last_update < now().date():
                try:
                    history = get_history_by_secid(
                        self.secid,
                        period='1d')
                except:
                    return 'no data', self.today_price, self.last_update
                max_day = max(history.keys())
                if force or max_day > self.last_update:
                    self.change_price_percent = (
                        Decimal(history[max_day]) - self.today_price)\
                        / self.today_price * 100
                    self.last_update = max_day
                    self.today_price = Decimal(history[max_day])
                    self.save()
                    refresh_price_security.send(
                        sender=self.__class__,
                        instance=self,
                        price=history[max_day])
                    return 'ok',\
                        history[max_day],\
                        max_day
            return 'already update', self.today_price, self.last_update
        elif self.source == 'rshb':
            if force or self.last_update < now().date():
                try:
                    result = rshb(self.parce_url,
                                  date=self.last_update,
                                  first=first)
                except Exception:
                    return 'no data', self.today_price, self.last_update
                if result:
                    if not force and \
                            result['date_publication'] <= self.last_update:
                        return 'no new data',\
                            self.today_price,\
                            self.last_update
                    else:
                        self.change_price_percent = (
                            Decimal(result['price_today']) - self.today_price)\
                            / self.today_price * 100
                        self.last_update = result['date_publication']
                        self.today_price = result['price_today']
                        self.save()
                        refresh_price_security.send(
                            sender=self.__class__,
                            instance=self,
                            price=result['price_today'])
                        return 'ok',\
                            result['price_today'],\
                            result['date_publication']
                return 'no data', self.today_price, self.last_update
            return 'already update', self.today_price, self.last_update
        elif self.source == 'cbr':
            try:
                res = refresh_valute_curse(self.name.replace('RUB', ''))
            except Exception:
                return 'no data', self.today_price, self.last_update
            date = datetime.strptime(res[1], '%d.%m.%Y').date()
            if self.last_update < date or force:
                self.today_price = res[0]
                self.last_update = date
                self.save()
                refresh_price_security.send(
                    sender=self.__class__,
                    instance=self,
                    price=self.today_price)
                return 'ok', self.today_price, date
            return 'already update', self.today_price, self.last_update
        elif self.source == 'moex':
            description = None
            if force or self.last_update < now().date():
                try:
                    result = moex_history(self.parce_url)

moex/forms.py
from django import forms
from .models import TradeHistory


class SearchForm(forms.Form):
    query = forms.CharField()


class TradeHistoryForm(forms.ModelForm):
    class Meta:
        model = TradeHistory
        exclude = ['owner', 'security', 'buy']

    def clean(self):
        cleaned_data = super().clean()
        count = cleaned_data.get("count")
        price = cleaned_data.get("price")
        commission = cleaned_data.get("commission")
        if 'count' in cleaned_data and count <= 0:
            self.add_error('count', 'Count must be more then zero')
        if 'price' in cleaned_data and price <= 0:
            self.add_error('price', 'Price must be more then zero')
        if 'commission' in cleaned_data and commission < 0:
            self.add_error('commission',
                           'Commission must be more or equal then zero')

vklad/forms.py
from django import forms
from .models import VkladInvestHistory
# from urllib import request
# from django.core.files.base import ContentFile
# from django.utils.text import slugify
# Create your forms here.


class FormVkladInvestHistory(forms.ModelForm):
    cash = forms.DecimalField(max_digits=10, decimal_places=2)
    date = forms.DateField()
    popolnenie = forms.BooleanField(required=False)

    class Meta:
        model = VkladInvestHistory
        exclude = ['vklad']

moex/templates/moex/detail.html
{% extends "base.html" %}
{% load static %}
{% load moex_extras %}
{% block page_css %}
  <link rel="stylesheet" href="{% static 'css/daterangepicker/daterangepicker.css' %}">
  <link rel="stylesheet" href="{% static 'css/toast/toast.css' %}">
{% endblock page_css %}

{% block content %}
<div class="container">
  <div class="mb-3 d-flex justify-content-between">
      <h3 class="align-self-center">{{ security.name }}</h3>
      {% if security.id %}
        {% if request.user in security.users_follows.all %}
          <a id="follow" class="btn btn-danger btn-sm align-self-center" href="{% url 'moex:follow' security.id %}">Отписаться</a>
        {% else %}
          <a id="follow" class="btn btn-primary btn-sm align-self-center" href="{% url 'moex:follow' security.id %}">Подписаться</a>
        {% endif %}
      {% endif %}
  </div>
  {% if request.user.is_staff and not security.id %}
  <form action="{% url 'moex:add_new_security_for_staff' security.secid %}" method="post">
    {% csrf_token %}
        <button type="submit" class="btn btn-success">Добавить в базу</button>
  </form>
  {% endif %}
    <div class="row">
      <div class="col-md-4">
        {% if security.url %}
          <a href="{{ security.url }}">Перейти на сайт</a>
        {% endif %}
        {% if security.security_type != 'currency' %}
          {% if security.fullname%}
            <p>Полное наименование: {{ security.fullname }}</p>
          {% endif %}
          {% if security.code %}
            <p>Код: {{ security.code }}</p>
          {% endif %}
          {% if security.regnumber %}
            <p>Рег.номер: {{ security.regnumber }}</p>
          {% endif %}
          {% if security.secid %}
            <p>SECID: {{ security.secid }}</p>
          {% endif %}
          {% if security.isin %}
            <p>ISIN: {{ security.isin }}</p>
          {% endif %}
        {% endif %}
        {% if security.facevalue %}
          <p>Номинальная стоимость: {{ security.facevalue }}</p>
        {% endif %}
        {% if security.issuesize %}
          <p>Объём выпуска: {{ security.issuesize }}</p>
        {% endif %}
        {% if security.main_board_faceunit and security.security_type != 'currency' %}
          <p>Валюта номинала: {{ security.get_main_board_faceunit_display }}</p>
        {% endif %}
        {% if security.initialfacevalue %}
          <p>Первоначальная номинальная стоимость: {{ security.initialfacevalue }}</p>
        {% endif %}
        {% if security.matdate %}
          <p>Дата погашения: {{ security.matdate }}</p>
        {% endif %}
        {% if security.coupondate %}
          <p>Дата выплаты купона: {{ security.coupondate }}</p>
        {% endif %}
        {% if security.couponfrequency %}
          <p>Периодичность выплаты купона в год: {{ security.couponfrequency }}</p>
        {% endif %}
        {% if security.couponpercent %}
          <p>Ставка купона (%): {{ security.couponpercent }}</p>
        {% endif %}
        {% if security.couponvalue %}
          <p>Сумма купона, в валюте номинала: {{ security.couponvalue }}</p>
        {% endif %}
        {% if security.accint %}
          <p>НКД: {{ security.accint }}</p>
        {% endif %}
        {% if security.emitent %}
          <p>Эмитент: {{ security.emitent }}</p>
        {% endif %}
        <p>Тип: {{ security.get_security_type_display }}</p>
        <p>Цена: {{ security.today_price|delete_zeroes }} {{ security.get_main_board_faceunit_display }} <span class="{% if security.change_price_percent > 0 %}text-success fas fa-angle-double-up{% elif security.change_price_percent < 0%}text-danger fas fa-angle-double-down{% else %}text-secondary{% endif %}">({{security.change_price_percent}}%)</span></p>
        <p>Дата обновления: {{ security.last_update }}</p>
        {% if security.description %}
        <p>Описание: {{ security.description }}</p>
        {% endif %}
      </div>

      <div class="col-md-8">
          <button type="button" class="btn btn-secondary mt-4 mb-2 col-12" id="historyBondButton" data-toggle="collapse" data-target="#collapseHistoryBond" aria-expanded="false" aria-controls="collapseHistoryBond">
            История цен
            </button>
        <div class="collapse" id="collapseHistoryBond">
          <div class="row">
              <div class="col-lg-4 .offset-lg-1 d-none d-md-block">
                <p>Дата</p>
              </div>
              <div class="col-lg-4 d-none d-md-block">
                <p>Цена</p>
              </div>
              <div class="col-lg-2 d-none d-md-block">
              </div>
          </div>
          <div id="preHistory" class="dropdown-divider d-none d-md-block"></div>
          <div id="spinnerHistory" class="row">
            <div class="col d-flex justify-content-center">
              <div class="spinner-border text-secondary" role="status">
                <span class="sr-only">Loading...</span>
              </div>
            </div>
          </div>
          {% if not new_security %}
                <a hidden id="load" class="btn btn-success btn-sm" href="{% url 'moex:get_security_history' security.id %}">Загрузить</a>
          {% else %}
                <a hidden id="load" class="btn btn-success btn-sm" href="{% url 'moex:get_new_security_history' security.secid %}">Загрузить</a>
          {% endif %}
        </div>
      {% if security_in_user_portfolios %}
        <button type="button" class="btn btn-secondary mt-4 mb-2 col-12" id="portfolioButton" data-toggle="collapse" data-target="#collapsePortfolio" aria-expanded="false" aria-controls="collapsePortfolio">
            Ваши портфели
            </button>
        <div class="collapse" id="collapsePortfolio">
          <div class="row">
              <div class="col-md-4 d-none d-md-block">
                <p>Портфель</p>
              </div>
              <div class="col-md-4 d-none d-md-block">
                <p>Количество</p>
              </div>
              <div class="col-md-2 d-none d-md-block">
              </div>
              <div class="col-md-2 d-none d-md-block">
              </div>
          </div>
          <div class="dropdown-divider d-none d-md-block"></div>
            {% for portfolio in security_in_user_portfolios %}
                <div class="row align-items-center">
                      <div class="col-lg-4 col-12 mb-1 mt-1">
                        <span class="d-md-none">Портфель: </span><a class="btn btn-warning btn-sm" href="{{ portfolio.portfolio.get_absolute_url }}">{{ portfolio.portfolio.title}}</a>
                      </div>
                      <div class="col-lg-4 col-12 mb-1 mt-1">
                        <span class="d-md-none">Количество: </span><span>{{ portfolio.count|delete_zeroes }} шт.</span>
                      </div>
                      <div class="col-lg-2 col-4 mb-1 mt-1">
                        <a class="btn btn-success btn-sm" href="{% url 'moex:buy' security.id %}?portfolio={{ portfolio.portfolio.id }}&buy=true">Купить</a>
                      </div>
                      <div class="col-lg-2 col-4 mb-1 mt-1">
                        <a class="btn btn-danger btn-sm" href="{% url 'moex:buy' security.id %}?portfolio={{ portfolio.portfolio.id }}&buy=false">Продать</a>
                      </div>
                </div>
                <div class="dropdown-divider"></div>
              {% endfor %}
        
        </div>
        {% else %}
          <h6 class="mt-4 mb-2 col-12">У вас в портфелях пока нет этой ценной бумаги.</h6>
        {% endif %}
      {% if not new_security %}
        {% if request.user|user_trades_security:security %}
            <button type="button" class="btn btn-secondary mt-4 mb-2 col-12" id="historyButton" data-toggle="collapse" data-target="#collapseHistory" aria-expanded="false" aria-controls="collapseHistory">
            История покупок
            </button>
            <div class="collapse" id="collapseHistory">
              <div class="row">
                <div class="col-md-2 d-none d-md-block">
                  <p>Количество</p>
                </div>
                <div class="col-md-2 d-none d-md-block">
                  <p>Цена</p>
                </div>
                <div class="col-md-2 d-none d-md-block">
                  <p>Комиссия</p>
                </div>
                <div class="col-md-2 d-none d-md-block">
                  <p>Действие</p>
                </div>
                <div class="col-md-2 d-none d-md-block">
                  <p>Дата</p>
                </div>
              </div>
              <div class="dropdown-divider d-none d-md-block"></div>
            {% for security in request.user|user_trades_security:security %}
              <div class="row align-items-center mt-2">
                      <div class="col-md-2 col-12 mb-1 mt-1">
                        <span class="d-md-none">Количество: </span><span>{{ security.count|delete_zeroes }} шт.</span>
                      </div>
                      <div class="col-md-2 col-12 mb-1 mt-1">
                        <span class="d-md-none">Цена: </span><span>{{ security.price|delete_zeroes }} {{ security.security.get_main_board_faceunit_display }}</span>
                      </div>
                      <div class="col-md-2 col-12 mb-1 mt-1">
                        <span class="d-md-none">Комиссия: </span><span>{{ security.commission|delete_zeroes }} руб.</span>
                      </div>
                      <div class="col-md-2 col-12 mb-1 mt-1">
                        <span class="d-md-none">Действие: </span><span>{% if security.buy %}Покупка{% else %}Продажа{% endif %}</span>
                      </div>
                      <div class="col-md-2 col-12 mb-1 mt-1">
                        <span class="d-md-none">Дата: </span><span>{{ security.date }}</span>
                      </div>
                  </div>
                  <a class="btn btn-danger btn-sm mb-1 mt-1" href="{% url 'moex:delete_history' security.id %}">Удалить запись</a>
                  <div class="dropdown-divider"></div>
            {% endfor %}
            </div>
        {% endif %}
      {% endif %}
      </div>
    </div>
</div>
{% endblock content %}

{% block domready %}
{% endblock domready %}


{% block page_javascript %}
    <script src="{% static 'js/follow.js' %}"></script>
    <script src="{% static 'js/toast/toast.js' %}"></script>
    <script src="{% static 'js/securyties_detail.js' %}"></script>
    <script src="{% static 'js/daterangepicker/moment.min.js' %}"></script>
    <script src="{% static 'js/daterangepicker/daterangepicker.js' %}"></script>
{% endblock page_javascript %}

moex/templates/moex/detail_new_vue.html
{% extends "base_with_vue.html" %}
{% load static %}

{% block content %}
  <div id="app">
    
  </div>
{% endblock content %}

{% block page_vue_scripts %}
    <script src="https://cdn.jsdelivr.net/npm/vuex@3.6.2/dist/vuex.min.js"></script>
    <script src="{% static 'vue/HTTP.js' %}"></script>
    <script src="{% static 'vue/errors.js' %}"></script>
    <script src="{% static 'vue/moex/store_detail_new.js' %}"></script>
    <script src="{% static 'vue/moex/components_detail_new.js' %}"></script>
    <script src="{% static 'vue/moex/main_detail_new.js' %}"></script>
{% endblock page_vue_scripts %}

moex/templates/moex/list.html
{% extends "base.html" %}
{% load static %}
{% load moex_extras%}
{% block page_css %}
            {% if request.user.is_staff %}
                <link rel="stylesheet" href="{% static 'css/toast/toast.css' %}">
            {% endif %}
{% endblock page_css %}

{% block content %}
<form action="." method="get">
    <div class="input-group mb-3">
      <input id="query" type="text" class="form-control" placeholder="Название" aria-label="search" aria-describedby="basic-addon2" name="query" {% if query %}value="{{ query }}"{% endif %}>
      <div class="input-group-append">
        <button class="btn btn-outline-secondary" type="submit">Поиск</button>
      </div>
    </div>
</form>
{% if securities %}
    <h3 class="mt-3 mb-3">Ценные бумаги:</h3>
    		{% include 'moex/securities_list_template.html'%}
    {% if securities.has_other_pages %}
      <div class="pagination">
        <span class="step-links">
            {% if securities.has_previous %}
            		{% if securities.previous_page_number != 1 %}
                	<a href="?page=1">&laquo; Первая</a>
                {% endif %}
                <a href="?page={{ securities.previous_page_number }}">Предыдущая</a>
            {% endif %}

            <span class="current">
                {{ securities.number }} из {{ securities.paginator.num_pages }}.
            </span>

            {% if securities.has_next %}
                <a href="?page={{ securities.next_page_number }}">Следующая</a>
                {% if securities.next_page_number != securities.paginator.num_pages %}
                	<a href="?page={{ securities.paginator.num_pages }}">Последняя &raquo;</a>
                {% endif %}
            {% endif %}
        </span>
    	</div>
    {% endif %}
{% else %}
<h3 class="mt-3 mb-3">По вашему запросу в нашей базе ничего не найдено.</h3>
{% endif %}
{% if 'query' in request.GET %}
<h3 id="moex_h3" class="mt-3 mb-3">Ценные бумаги из других источников:</h3>
{% endif %}
{% if moex_dict %}
<button type="button" class="btn btn-secondary col-12 mb-2" id="buttonMoexList" data-toggle="collapse" data-target="#collapseMoexList" aria-expanded="false" aria-controls="collapseMoexList">
            Развернуть
            </button>
<div class="collapse" id="collapseMoexList">
  <small id="moex_list" hidden="false">True</small>
    <div class="row">
        <div class="col-md-3 d-none d-md-block">
          <p>Наименование</p>
        </div>
        <div class="col-md-3 d-none d-md-block">
          <p>Эмитент</p>
        </div>
        <div class="col-md-2 d-none d-md-block">
          <p>SECID</p>
        </div>
        <div class="col-md-2 d-none d-md-block">
          <p>ISIN</p>
        </div>
        <div class="col-md-2 d-none d-md-block">
          <p>Regnumber</p>
        </div>
    </div>
    <div class="dropdown-divider"></div>
    {% for secid,value in moex_dict.items %}
        <div class="row">
              <div class="col-md-3">
                <span class="d-md-none">Наименование: </span><a class="btn btn-warning btn-sm" href="{% url 'moex:new_detail' secid %}">{{ value.shortname }}</a>
              </div>
              <div class="col-md-3">
                <span class="d-md-none">Эмитент: </span><span>{{ value.emitent }}</span>
              </div>
              <div class="col-md-2">
                <span class="d-md-none">SECID: </span><span>{{ secid }}</span>
              </div>
              <div class="col-md-2">
                <span class="d-md-none">ISIN: </span><span>{{ value.isin }}</span>
              </div>
              <div class="col-md-2">
                <span class="d-md-none">Regnumber: </span><span>{{ value.regnumber }}</span>
              </div>
        </div>
        <div class="dropdown-divider d-none d-md-block"></div>
    {% endfor %}
</div>
{% else %}
{% if 'query' in request.GET %}
<div id="spiner_moex" class="d-flex justify-content-center">
  <div class="spinner-border" role="status">
    <span class="sr-only">Loading...</span>
  </div>
</div>
<small id="moex_list" hidden="false">False</small>
{% endif %}
{% endif %}
{% endblock content %}

{% block page_javascript %}
          {% if 'query' in request.GET %}
            <script src="{% static 'js/securyties_list_moex.js' %}"></script>
          {% endif %}
            {% if request.user.is_staff %}
                <script src="{% static 'js/securyties_list.js' %}"></script>
                <script src="{% static 'js/toast/toast.js' %}"></script>
            {% endif %}
{% endblock page_javascript %}

moex/templates/moex/securities_list_template.html
{% load moex_extras%}
<div class="row">
    		          <div class="col-md-4 d-none d-md-block">
    		            <p>Наименование</p>
    		          </div>
    		          <div class="col-md-4 d-none d-md-block">
    		            <p>Эмитент</p>
    		          </div>
    		          <div class="col-md-2 d-none d-md-block">
    		            <p>Цена</p>
    		          </div>
                  <div class="col-md-2 d-none d-md-block">
                    <p>Дата обновления</p>
                  </div>
    	        </div>
    	    <div class="dropdown-divider d-none d-md-block"></div>
    		{% for security in securities %}
            <div class="row">
                  <div class="col-md-4 mb-1 mt-1">
                    <span class="d-md-none">Наименование: </span><a class="btn btn-warning btn-sm" href="{{ security.get_absolute_url }}">{{ security.name }}</a>
                  </div>
                  <div class="col-md-4 mb-1 mt-1">
                    <span class="d-md-none">Эмитент: </span><span>{{ security.emitent }}</span>
                  </div>
                	<div class="col-md-2 mb-1 mt-1">
                    <span class="d-md-none">Цена: </span><span id="{{ security.id }}">{{ security.today_price|delete_zeroes }}</span><span> {{ security.get_main_board_faceunit_display }}<br class="d-none d-md-inline"><span class="d-md-none d-inline"> </span><span class="{% if security.change_price_percent > 0 %}text-success fas fa-angle-double-up{% elif security.change_price_percent < 0%}text-danger fas fa-angle-double-down{% else %}text-secondary{% endif %}">({{security.change_price_percent}}%)</span></span>
                  </div>
                  <div class="col-md-2 mb-1 mt-1">
                    <span class="d-md-none">Дата обновления: </span><span id="{{ security.id }}_last_update">{{ security.last_update }}</span>
                  </div>
                  {% if request.user.is_staff %}
                    <div class="col-md-2 mb-1 mt-1">
                    <a class="refresh_security btn btn-success btn-sm mt-1 mb-2" href="{% url 'moex:refresh_security' security.id %}">Обновить</a>
                  </div>
                  {% endif %}
            </div>
            <div class="dropdown-divider"></div>
        {% endfor %}