config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView
from rest_framework.authtoken.views import obtain_auth_token
from django.http import HttpResponse
from .views import HomePageView
from bonds.users.views import CustomUserSignUp


def favicon(request):
    image_data = open(settings.STATIC_ROOT + "/images/favicons/favicon.ico",
                      "rb").read()
    return HttpResponse(image_data, content_type="image/png")


urlpatterns = [
    path("", HomePageView.as_view(), name="home"),
    path("about/",
         TemplateView.as_view(template_name="pages/about.html"),
         name="about"),
    path("privacy/",
         TemplateView.as_view(template_name="pages/privacy.html"),
         name="privacy"),
    path("faq/",
         TemplateView.as_view(template_name="pages/faq.html"),
         name="faq"),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("bonds.users.urls", namespace="users")),
    path("accounts/signup/",\
         CustomUserSignUp.as_view(),\
         name="signup"),
    path("accounts/", include("allauth.urls")),
    path("portfolio/", include("portfolio.urls", namespace="portfolio")),
    path("vklad/", include("vklad.urls", namespace="vklad")),
    path("securities/", include("moex.urls", namespace="moex")),
    path("friends/", include("friends.urls", namespace="friends")),
    path("breports/", include("breports.urls", namespace="breports")),
    path("tgwebhook/", include("tgbot.urls", namespace="tgbot")),
    path("favicon.ico", favicon, name="favicon"),
    # Your stuff: custom urls includes go here
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# API URLS
urlpatterns += [
    # API base url
    path("api/", include("config.api_router")),
    # DRF auth token
    path("auth-token/", obtain_auth_token),
]

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]

    # django-silk urls
    if "silk" in settings.INSTALLED_APPS:
        urlpatterns += [path('silk/', include('silk.urls', namespace='silk'))]

    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [
            path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

moex/urls.py
from django.urls import path
from . import views

# create your routs

app_name = 'moex'

urlpatterns = [

    path('search_moex/', views.security_search_moex, name='search_moex'),
    path('buy/<int:id>/', views.security_buy, name='buy'),
    path('delete_history/<int:id>/',
         views.delete_history,
         name='delete_history'),
    path('detail2/<int:id>/', views.security_detail, name='detail_old'),
    path('detail/<int:id>/', views.security_detail_vue, name='detail'),
    path('detail-new-old/<secid>/', views.new_security_detail, name='new_detail'),
    path('detail-new/<str:s>/', views.new_security_detail_vue, name='new_detail_vue'),
    path('buy-new/<secid>/', views.new_security_buy, name='new_buy'),
    path('add-new/<secid>/', views.add_new_security_for_staff,
         name='add_new_security_for_staff'),
    path('new_security_history/<secid>/',
         views.get_new_security_history, name='get_new_security_history'),
    path('refresh/<int:id>/', views.refresh_security, name='refresh_security'),
    path('follow/<int:id>/', views.security_follow, name='follow'),
    path('sp/<int:id_p>/<int:id_s>/', views.sp, name='sp'),
    path('security_history/<int:id>/',
         views.get_security_history, name='get_security_history'),
    path('old-list/', views.security_list, name='list-old'),
    path('', views.security_list_vue, name='list'),
]

vklad/urls.py
from django.urls import path
from . import views

# create your routs

app_name = 'vklad'

urlpatterns = [
    path('add_vklad/<int:id>/', views.add_vklad,
         name='add_vklad'),
    path('del_vklad/<int:id>/', views.del_vklad,
         name='del_vklad'),
    path('refresh_vklad/<int:id>/', views.refresh_vklad,
         name='refresh_vklad'),
    path('', views.detail_vklad,
         name='detail_vklad'),
]

vklad/models.py
from django.db import models
from bonds.users.models import User
from django.urls import reverse
from portfolio import scripts
from django.dispatch import receiver
from django.db.models.signals import post_save
from django.db.models import Prefetch
from portfolio.models import PortfolioInvestHistory
# Create your models here.


class UserVklad(models.Model):
    owner = models.OneToOneField(User, on_delete=models.CASCADE,
                                 related_name='vklad')
    invest_cash = models.DecimalField(max_digits=10, decimal_places=2,
                                      default=0)
    today_cash = models.DecimalField(max_digits=10, decimal_places=2,
                                     default=0)
    ostatok = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    created = models.DateTimeField(auto_now_add=True, db_index=True)
    percent_profit = models.DecimalField(max_digits=5, decimal_places=2,
                                         default=0)
    year_percent_profit = models.DecimalField(max_digits=5, decimal_places=2,
                                              default=0)

    def calc_invest_cash(self):
        user = self.owner
        self.invest_cash = sum(
            [i.invest_cash for i in user.portfolios.all()]
        )

    def calc_percent_profit(self):
        self.percent_profit = scripts.percent_profit(self.today_cash,
                                                     self.invest_cash)

    def calc_today_cash(self):
        t = self.owner.portfolios.all()
        total = [i.today_cash for i in t]
        self.today_cash = sum(total)

    def calc_year_percent_profit(self):
        portfolios = self.owner.portfolios.all()
        queryset = PortfolioInvestHistory.objects.filter(
            action__in=['vp', 'pv'])
        prefecth = Prefetch('portfolio_invests',
                            queryset=queryset,
                            to_attr='invests')
        portfolio_invests = portfolios.prefetch_related(prefecth)
        res = [item for sublist in portfolio_invests
               for item in sublist.invests]
        invests = [[i.cash_in_rub * (-1)**(i.action == 'pv'), i.date] for i in res]
        self.year_percent_profit = scripts.year_percent_profit(
            invests, self.today_cash)

    def refresh_vklad(self):
        self.calc_invest_cash()
        self.calc_today_cash()
        try:
            self.calc_percent_profit()
        except ZeroDivisionError:
            return
        self.calc_year_percent_profit()
        self.save()

    def get_absolute_url(self):
        return reverse('vklad:detail_vklad')


@receiver(post_save, sender=User)
def create_user_vklad(sender, instance, created, **kwargs):
    if created:
        UserVklad.objects.create(owner=instance)


class VkladHistory(models.Model):
    vklad = models.ForeignKey(UserVklad, on_delete=models.CASCADE,
                              related_name='vklad_historyes')
    date = models.DateField()
    percent_profit = models.DecimalField(max_digits=5,
                                         decimal_places=2, default=0)
    year_percent_profit = models.DecimalField(max_digits=5,
                                              decimal_places=2, default=0)

    class Meta:
        ordering = ['-date']

    def calc_percent_profit(self):
        pass

    def calc_year_percent_profit(self):
        pass


class VkladInvestHistory(models.Model):
    vklad = models.ForeignKey(
        UserVklad, related_name='vklads', on_delete=models.CASCADE)
    date = models.DateField()
    cash = models.DecimalField(max_digits=10,
                               decimal_places=2, default=0)
    popolnenie = models.BooleanField(default=True)

    def save(self, *args, **kwargs):
        if not self.popolnenie:
            if self.cash > self.vklad.ostatok:
                return 'no money'
            self.vklad.ostatok -= self.cash
        else:
            self.vklad.ostatok += self.cash
        super(VkladInvestHistory, self).save(*args, **kwargs)
        self.vklad.refresh_vklad()
        return 'ok'

    def delete(self, *args, **kwargs):
        if self.popolnenie:
            if self.cash <= self.vklad.ostatok:
                self.vklad.ostatok -= self.cash
            else:
                return 'no_money'
        else:
            self.vklad.ostatok += self.cash
        super(VkladInvestHistory, self).delete(*args, **kwargs)
        self.vklad.refresh_vklad()
        return 'ok'

    class Meta:
        ordering = ['-date', 'cash']

vklad/forms.py
from django import forms
from .models import VkladInvestHistory
# from urllib import request
# from django.core.files.base import ContentFile
# from django.utils.text import slugify
# Create your forms here.


class FormVkladInvestHistory(forms.ModelForm):
    cash = forms.DecimalField(max_digits=10, decimal_places=2)
    date = forms.DateField()
    popolnenie = forms.BooleanField(required=False)

    class Meta:
        model = VkladInvestHistory
        exclude = ['vklad']

vklad/views.py
from django.shortcuts import render, get_object_or_404
from django.views.decorators.http import require_POST
from django.contrib.auth.decorators import login_required
import portfolio
from portfolio.models import PortfolioInvestHistory
from .forms import FormVkladInvestHistory
from .models import UserVklad, VkladInvestHistory
from django.core.exceptions import ObjectDoesNotExist
from django.http import JsonResponse
# Create your views here.


def updated_vklad(vklad):
    return {'invest_cash': str(vklad.invest_cash),
            'today_cash': str(vklad.today_cash),
            'ostatok': str(vklad.ostatok),
            'percent_profit': str(vklad.percent_profit),
            'year_percent_profit': str(vklad.year_percent_profit),
            }


@login_required
def detail_vklad(request):
    user = request.user
    vklad = user.vklad
    # form = FormVkladInvestHistory()
    portfolios = user.portfolios.all()
    invests = PortfolioInvestHistory.objects.filter(
        portfolio__in=portfolios
    ).select_related('security', 'portfolio')
    trades = user.trades.select_related('security', 'portfolio').all()
    return render(request,
                  'vklad/detail.html',
                  {'vklad': vklad,
                   'invests': invests,
                   'portfolios': portfolios,
                   'trades': trades,
                   # 'form': form,
                   'user': user})


@login_required
@require_POST
def add_vklad(request, id):
    form = FormVkladInvestHistory(data=request.POST)
    print(request.POST)
    if form.is_valid():
        try:
            vklad = get_object_or_404(UserVklad, id=id)
            if vklad.owner == request.user:
                new_item = form.save(commit=False)
                new_item.vklad = vklad
                status = new_item.save()
                content = {'status': status}
                if status == 'ok':
                    content.update({'id': str(new_item.id)})
                    content.update(updated_vklad(vklad))
                return JsonResponse(content)
        except ObjectDoesNotExist:
            return JsonResponse({'status': 'no_id'})
    return JsonResponse({'status': 'no_valid'})


@require_POST
@login_required
def del_vklad(request, id):
    try:
        vklad = get_object_or_404(VkladInvestHistory, id=id)
        if vklad.vklad.owner == request.user:
            status = vklad.delete()
            content = {'status': status}
            if status == 'ok':
                content.update(updated_vklad(vklad.vklad))
            return JsonResponse(content)
    except ObjectDoesNotExist:
        return JsonResponse({'status': 'no_id'})


@login_required
def refresh_vklad(request, id):
    try:
        vklad = get_object_or_404(UserVklad, id=id)
        if vklad.owner == request.user:
            vklad.refresh_vklad()
            content = {'status': 'ok'}
            content.update(updated_vklad(vklad))
            return JsonResponse(content)
    except ObjectDoesNotExist:
        return JsonResponse({'status': 'no_id'})

vklad/templates/vklad/detail.html
{% extends "base.html" %}
{% load static %}
{% load moex_extras %}
{% block page_css %}
<link rel="stylesheet" href="{% static 'css/daterangepicker/daterangepicker.css' %}">
<link rel="stylesheet" href="{% static 'css/toast/toast.css' %}">

{% endblock page_css %}

{% block content %}
<div class="container">
    <h3>Мой кошелёк:</h3>
    <div class="row">
        <div class="col-md-4">
            <p>Всего инвестиций: <span id="invest_cash">{{vklad.invest_cash}}</span></p>
            <p>Текущий баланс: <span id="today_cash">{{vklad.today_cash}}</span></p>
       {% comment "" %}<p>Остаток: <span id="ostatok">{{vklad.ostatok}}</span></p>{% endcomment %} 
            <p>Доходность: <span id="percent_profit">{{vklad.percent_profit}}</span></p>
            <p>Годовая доходность: <span id="year_percent_profit">{{vklad.year_percent_profit}}</span></p>
        {% comment "" %}<a class="mb-4 refresh-vklad btn btn-info btn-sm" href="{% url 'vklad:refresh_vklad' vklad.id %}">Обновить</a>{% endcomment %} 
</div>

        <div class="col-md-8">
            <button type="button" class="btn btn-secondary mt-4 mb-2 col-12" id="historyPortfolioButton" data-toggle="collapse" data-target="#collapseHistoryVklad" aria-expanded="false" aria-controls="collapseHistoryVklad">
            История пополнений и снятий
            </button>
            <div class="collapse history-table" id="collapseHistoryVklad">
                {% for i in invests %}
                    <div class="row align-items-center">
                        <div class="col-9">
                            <div class="row">
                                <div class="col-md-4">
                                    {{ i.date }}
                                </div>
                                <div class="col-md-4">
                                    {{ i.cash }} {{ i.get_currency_display }}
                                    {% if i.currency != 'SUR' %}</br>({{ i.cash_in_rub }} РУБ){% endif %}
                                </div>
                                <div class="col-md-4">
                                    {{ i.get_action_display }}
                                    {% if i.security %}
                                        </br>
                                        <a class="btn btn-warning btn-sm" href="{% url 'moex:detail' i.security.id %}">{{ i.security.shortname }}</a>
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                        <div class="col-3">
                            <a class="btn btn-secondary btn-sm" href="{% url 'portfolio:detail' i.portfolio.id %}">{{ i.portfolio.title }}</a>
                        </div>
                    </div>
                    <div class="dropdown-divider"></div>
                
                {% endfor %}
                {% comment "перечень инвест позиций вклада" %}
                {% for i in vklad.vklads.all %}
                    <div class="row align-items-center">
                        <div class="col-9">
                            <div class="row">
                                <div class="col-md-4">
                                    {{ i.date }}
                                </div>
                                <div class="col-md-4">
                                    {{ i.cash }}
                                </div>
                                <div class="col-md-4">
                                    {% if i.popolnenie %}Пополнение{% else %}Снятие{% endif %}
                                </div>
                            </div>
                        </div>
                        <div class="col-3">
                            <a class="delete-vklad btn btn-danger btn-sm" href="{% url 'vklad:del_vklad' i.id %}">Удалить</a>
                        </div>
                    </div>
                    <div class="dropdown-divider"></div>
                {% endfor %}
                {% endcomment %}

                {% comment "форма добавления на вклад" %}
                <div class="row align-items-center">
                    <div class="col-9">
                            <div class="row align-items-center">
                                <div class="col-md-4"><input type="text" name="date" required="" id="id_date" class="form-control form-control-sm mt-1 mb-2"></div>
                                <div class="col-md-4"><input type="number" name="cash" step="0.01" required="" id="id_cash" class="form-control form-control-sm mt-1 mb-2" placeholder="Введите сумму"></div>
                                <div class="col-md-4"><input type="checkbox" name="popolnenie" id="id_popolnenie"> <label for="id_popolnenie">Пополнение</label></div>
                            </div>
                    </div>
                    <div class="col-3">
                        <a id="add_vklad" class="btn btn-success btn-sm mt-1 mb-2" href="{% url 'vklad:add_vklad' vklad.id %}">Добавить</a>
                    </div>
                </div>
                {% endcomment %}
            </div>
            <button type="button" class="btn btn-secondary mt-4 mb-2 col-12" id="PortfolioButton" data-toggle="collapse" data-target="#collapsePortfolios" aria-expanded="false" aria-controls="collapsePortfolios">
                Портфели
            </button>
            <div class="collapse history-table" id="collapsePortfolios">
                <div class="row">
                    <div class="col-md-2 d-none d-md-block">
                        <p>Наименование</p>
                    </div>
                    <div class="col-md-2 d-none d-md-block">
                        <p>Инвестиции</p>
                    </div>
                    <div class="col-md-2 d-none d-md-block">
                        <p>Текущий баланс</p>
                    </div>
                    <div class="col-md-2 d-none d-md-block">
                        Доходность
                    </div>
                    <div class="col-md-2 d-none d-md-block">
                    Годовая доходность
                    </div>
                </div>
                {% for portfolio in portfolios %}
                    <div class="dropdown-divider"></div>
                    <div class="row">
                        <div class="col-md-2 mt-1 mb-1">
                            <a class="btn btn-secondary btn-sm" href="{{ portfolio.get_absolute_url }}">{{ portfolio.title}}</a>
                        </div>
                        <div class="col-md-2 mt-1 mb-1">
                            <span class="d-md-none">Инвестиции: </span>{{ portfolio.invest_cash}}
                        </div>
                        <div class="col-md-2 mt-1 mb-1">
                            <span class="d-md-none">Текущий баланс: </span>{{ portfolio.today_cash}}<br class="d-none d-md-inline"><span class="d-md-none d-inline"> </span><span class="{{ portfolio.change_today_cash | return_color_and_fas_bootstrap:True }}"><span class="d-md-none d-inline"></span>({{portfolio.change_today_cash}}%)</span>
                        </div>
                        <div class="col-md-2 mt-1 mb-1">
                            <span class="d-md-none">Доходность: </span>
                            <span class="{{ portfolio.percent_profit | return_color_and_fas_bootstrap }}">{{ portfolio.percent_profit }}%</span><br class="d-none d-md-inline"><span class="d-md-none d-inline"> </span><span class="{{ portfolio.change_percent_profit | return_color_and_fas_bootstrap:True }}"><span class="d-md-none d-inline"></span>({{portfolio.change_percent_profit}}%)</span>
                        </div>
                        <div class="col-md-2 mt-1 mb-1">
                            <span class="d-md-none">Годовая доходность: </span>
                            <span class="{{ portfolio.year_percent_profit | return_color_and_fas_bootstrap }}">{{ portfolio.year_percent_profit }}%</span><br class="d-none d-md-inline"><span class="d-md-none d-inline"> </span><span class="{{ portfolio.change_year_percent_profit | return_color_and_fas_bootstrap:True }}"><span class="d-md-none d-inline"></span>({{portfolio.change_year_percent_profit}}%)</span>
                        </div>
                    </div>
                    
                {% endfor %}
            </div>
            <button type="button" class="btn btn-secondary mt-4 mb-2 col-12" 
            id="TradesButton" data-toggle="collapse" data-target="#collapseTrades" aria-expanded="false" aria-controls="collapseTrades">
                История торгов
            </button>
            <div class="collapse history-table" id="collapseTrades">
                <div class="row">
                    <div class="col-md-2 mt-1 d-none d-md-block">
                        <p>Портфель</p>
                    </div>
                    <div class="col-md-2 mt-1 d-none d-md-block">
                        <p>Ценная бумага</p>
                    </div>
                    <div class="col-md-2 mt-1 d-none d-md-block">
                        <p>Количество</p>
                    </div>
                    <div class="col-md-2 mt-1 d-none d-md-block">
                        <p>Цена</p>
                    </div>
                    <div class="col-md-2 mt-1 d-none d-md-block">
                        <p>Действие</p>
                    </div>
                    <div class="col-md-2 mt-1 d-none d-md-block">
                        <p>Дата</p>
                    </div>
                </div>
                {% for trade in trades %}
                    <div class="dropdown-divider"></div>
                    <div class="row">
                        <div class="col-md-2 mt-1 mb-1">
                            <a class="btn btn-secondary btn-sm" href="{{ trade.portfolio.get_absolute_url }}">{{ trade.portfolio.title }}</a>
                        </div>
                        <div class="col-md-2 mt-1 mb-1">
                            <a class="btn btn-warning btn-sm" href="{% url 'moex:detail' trade.security.id %}">{{ trade.security.shortname }}</a>
                        </div>
                        <div class="col-md-2 mt-1 mb-1">
                            <span class="d-md-none">Количество: </span><span>{{ trade.count|delete_zeroes }} шт.</span>
                        </div>
                        <div class="col-md-2 mt-1 mb-1">
                            <span class="d-md-none">Цена: </span>
                            <span>{{ trade.price|delete_zeroes }} {{ trade.security.get_main_board_faceunit_display }}</span>
                            {% if trade.commission > 0 %}
                                </br>
                                <span>Комиссия: </span>
                                <span>{{ trade.commission|delete_zeroes }} {{ trade.security.get_main_board_faceunit_display }}</span>
                            {% endif %}
                            {% if trade.nkd > 0 %}
                                </br>
                                <span>НКД: </span>
                                <span>{{ trade.nkd|delete_zeroes }} {{ trade.security.get_main_board_faceunit_display }}</span>
                            {% endif %}
                            {% if trade.ndfl > 0 %}
                                </br>
                                <span>НДФЛ: </span>
                                <span>{{ trade.ndfl|delete_zeroes }} {{ trade.security.get_main_board_faceunit_display }}</span>
                            {% endif %}
                        </div>
                        <div class="col-md-2 mt-1 mb-1">
                            <span class="d-md-none">Действие: </span><span>{% if trade.buy %}Покупка{% else %}Продажа{% endif %}</span>
                        </div>
                        <div class="col-md-2 mt-1 mb-1">
                            <span class="d-md-none">Дата: </span><span>{{ trade.date }}</span>
                        </div>


                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
</div>


{% endblock content %}


{% block domready %}
        
{% endblock domready %}

{% block page_javascript %}

    <script src="{% static 'js/daterangepicker/moment.min.js' %}"></script>
    <script src="{% static 'js/daterangepicker/daterangepicker.js' %}"></script>
    <script src="{% static 'js/toast/toast.js' %}"></script>
    <script src="{% static 'js/vklad_detail.js' %}"></script>
    
{% endblock page_javascript %}