bonds/users/urls.py
from django.urls import path

from bonds.users.views import (
    user_detail_view,
    user_redirect_view,
    user_update_view,
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

friends/urls.py
from django.urls import path
from . import views

# create your routs

app_name = 'friends'

urlpatterns = [
    path('friends_request_reject/<int:id>/',
         views.friends_request_reject, name='friends_request_reject'),
    path('friends_request_cancel/<int:id>/',
         views.friends_request_cancel, name='friends_request_cancel'),
    path('friends_send_request/<int:id>/',
         views.friends_send_request, name='friends_send_request'),
    path('friends_request_accept/<int:id>/',
         views.friends_request_accept, name='friends_request_accept'),
    path('friends_delete/<int:id>/',
         views.friends_delete, name='friends_delete'),
    path('', views.friends_list, name='list'),
]

moex/urls.py
from django.urls import path
from . import views

# create your routs

app_name = 'moex'

urlpatterns = [

    path('search_moex/', views.security_search_moex, name='search_moex'),
    path('buy/<int:id>/', views.security_buy, name='buy'),
    path('delete_history/<int:id>/',
         views.delete_history,
         name='delete_history'),
    path('detail2/<int:id>/', views.security_detail, name='detail_old'),
    path('detail/<int:id>/', views.security_detail_vue, name='detail'),
    path('detail-new-old/<secid>/', views.new_security_detail, name='new_detail'),
    path('detail-new/<str:s>/', views.new_security_detail_vue, name='new_detail_vue'),
    path('buy-new/<secid>/', views.new_security_buy, name='new_buy'),
    path('add-new/<secid>/', views.add_new_security_for_staff,
         name='add_new_security_for_staff'),
    path('new_security_history/<secid>/',
         views.get_new_security_history, name='get_new_security_history'),
    path('refresh/<int:id>/', views.refresh_security, name='refresh_security'),
    path('follow/<int:id>/', views.security_follow, name='follow'),
    path('sp/<int:id_p>/<int:id_s>/', views.sp, name='sp'),
    path('security_history/<int:id>/',
         views.get_security_history, name='get_security_history'),
    path('old-list/', views.security_list, name='list-old'),
    path('', views.security_list_vue, name='list'),
]

bonds/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db.models import CharField, BooleanField
from django.urls import reverse
from django.utils.translation import ugettext_lazy as _


class User(AbstractUser):

    # First Name and Last Name do not cover name patterns
    # around the globe.
    name = CharField(_("Name of User"), blank=True, max_length=255)
    accept_private_policy = BooleanField(
        "Согласие с политикой конфиденциальности", default=False)

    def get_absolute_url(self):
        return reverse("users:detail", kwargs={"username": self.username})

bonds/users/forms.py
from django.contrib.auth import forms, get_user_model
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _
from allauth.account import forms as allauth_forms
from django import forms as django_forms
User = get_user_model()


class UserChangeForm(forms.UserChangeForm):
    class Meta(forms.UserChangeForm.Meta):
        model = User


class UserCreationForm(forms.UserCreationForm):

    error_message = forms.UserCreationForm.error_messages.update(
        {"duplicate_username": _("This username has already been taken.")}
    )

    class Meta(forms.UserCreationForm.Meta):
        model = User

    def clean_username(self):
        username = self.cleaned_data["username"]

        try:
            User.objects.get(username=username)
        except User.DoesNotExist:
            return username

        raise ValidationError(self.error_messages["duplicate_username"])


class CustomSignUpForm(allauth_forms.SignupForm):
    privacy_politic_accept = django_forms.BooleanField(
        label='С политикой конфиденциальности согласен')

    def __init__(self, *args, **kwargs):
        super(CustomSignUpForm, self).__init__(*args, **kwargs)
        self.order_fields(['email',
                           'username',
                           'password1',
                           'password2',
                           'privacy_politic_accept'])

    def save(self, *args, **kwargs):
        user = super(CustomSignUpForm, self).save(*args, **kwargs)
        user.accept_private_policy = True
        user.save()
        return user

vklad/forms.py
from django import forms
from .models import VkladInvestHistory
# from urllib import request
# from django.core.files.base import ContentFile
# from django.utils.text import slugify
# Create your forms here.


class FormVkladInvestHistory(forms.ModelForm):
    cash = forms.DecimalField(max_digits=10, decimal_places=2)
    date = forms.DateField()
    popolnenie = forms.BooleanField(required=False)

    class Meta:
        model = VkladInvestHistory
        exclude = ['vklad']

bonds/users/api/views.py
from django.contrib.auth import get_user_model
from rest_framework import status
from rest_framework.decorators import action
from rest_framework.mixins import ListModelMixin,\
    RetrieveModelMixin,\
    UpdateModelMixin
from rest_framework.response import Response
from rest_framework.viewsets import GenericViewSet

from .serializers import UserSerializer

User = get_user_model()


class UserViewSet(RetrieveModelMixin,
                  ListModelMixin,
                  UpdateModelMixin,
                  GenericViewSet):
    serializer_class = UserSerializer
    queryset = User.objects.all()
    lookup_field = "username"

    def get_queryset(self, *args, **kwargs):
        return self.queryset.filter(id=self.request.user.id)

    @action(detail=False, methods=["GET"])
    def me(self, request):
        serializer = UserSerializer(request.user, context={"request": request})
        return Response(status=status.HTTP_200_OK, data=serializer.data)

bonds/users/views.py
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.utils.translation import ugettext_lazy as _
from django.views.generic import DetailView, RedirectView, UpdateView
from allauth.account.views import SignupView
from .forms import CustomSignUpForm
from vklad.forms import FormVkladInvestHistory

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    slug_field = "username"
    slug_url_kwarg = "username"

    def get_context_data(self, **kwargs):
        context = super(UserDetailView, self).get_context_data(**kwargs)
        context['form'] = FormVkladInvestHistory()
        return context


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, UpdateView):

    model = User
    fields = ["name"]

    def get_success_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})

    def get_object(self):
        return User.objects.get(username=self.request.user.username)

    def form_valid(self, form):
        messages.add_message(
            self.request, messages.INFO, _("Infos successfully updated")
        )
        return super().form_valid(form)


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):

    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail",
                       kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()


class CustomUserSignUp(SignupView):
    form_class = CustomSignUpForm

bonds/templates/users/email_informer_template.html
{% load email_extras %}
{% load moex_extras %}
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <title>{{ subject }}</title>
        <style media="all" type="text/css">
       {# or use bootstrap_email_min for stripped file #}
    </style>
</head>
<body>
	{% if portfolios %}
		<h3>Мои портфели:</h3>
		{% include "users/portfolios_template.html" with portfolios=portfolios %}
	{% endif %}

	{% if securities_in_portfolios %}
    <h3>Ценные бумаги в портфелях:</h3>
        {% include "users/securities_template.html" with securities=securities_in_portfolios %}
    {% endif %}

    {% if portfolio_followed %}
        <h3>Отслеживаемые портфели:</h3>
        {% include "users/portfolios_template.html" with portfolios=portfolio_followed %}
    {% endif %}

    {% if security_followed %}
    <h3>Отслеживаемые ценные бумаги:</h3>
        {% include "users/securities_template.html" with securities=security_followed %}
    {% endif %}

</body>
</html>

bonds/templates/users/portfolios_template.html
{% load email_extras %}
{% load moex_extras %}

{% for portfolio in portfolios %}
	<h5>*{{ portfolio.title}}</h5>
		{% if portfolio.owner != request.user %}
			<p>Владелец: {{ portfolio.owner }}</p>
		{% endif %}
        <p>Инвестиции: {{ portfolio.invest_cash }}</p>
        <p>Текущий баланс: {{ portfolio.today_cash }}</span> <span style = "color:{{portfolio.change_today_cash | return_color }}">({{portfolio.change_today_cash | return_number_with_sign}}%)</span></p>
        <p>Доходность: </span><span style = "color:{{portfolio.percent_profit | return_color }}">{{ portfolio.percent_profit}}%</span> <span style = "color:{{portfolio.change_percent_profit | return_color }}">({{portfolio.change_percent_profit | return_number_with_sign }}%)</p>
       <p>Годовая доходность: </span><span style = "color:{{portfolio.year_percent_profit | return_color }}">{{ portfolio.year_percent_profit }}%</span> <span style = "color:{{portfolio.change_year_percent_profit | return_color }}">({{portfolio.change_year_percent_profit | return_number_with_sign}}%)</p>
       <p>---------------------------</span></p>
{% endfor %}

bonds/templates/users/securities_template.html
{% load email_extras %}
{% load moex_extras %}

{% for security in securities %}
    <h5>Наименование: </span>{{ security.name }}</h5>
    <p>Эмитент: </span><span>{{ security.emitent }}</p>
    <p>Цена: </span><span>{{ security.today_price | delete_zeroes }}</span><span> руб. <span style = "color:{{security.change_price_percent | return_color }}">({{security.change_price_percent | return_number_with_sign}}%)</span></p>
    <p>Дата обновления: </span><span>{{ security.last_update }}</p>
    <p>---------------------------</p>
{% endfor %}

bonds/templates/users/user_detail.html
{% extends "base.html" %}
{% load static %}{% load friends_extras %}

{% block page_css %}
<link rel="stylesheet" href="{% static 'css/daterangepicker/daterangepicker.css' %}">
<link rel="stylesheet" href="{% static 'css/toast/toast.css' %}">
{% endblock page_css %}

{% block title %}User: {{ object.username }}{% endblock %}

{% block content %}
<div class="container">

  <div class="row">
    <div class="col-sm-12">

      <h2>{{ object.username }}</h2>
      {% if object.name %}
        <p>{{ object.name }}</p>
      {% endif %}
    </div>
  </div>

    {% if object == request.user %}
    <!-- Action buttons -->
        <div class="row">

            <div class="col-sm-12">
                <a class="btn btn-primary" href="{% url 'users:update' %}" role="button">My Info</a>
                <a class="btn btn-primary" href="{% url 'account_email' %}" role="button">E-Mail</a>
                <a class="btn btn-primary" href="{% url 'socialaccount_connections' %}" role="button">Прикрепленные аккаунты социльных сетей</a>
                <a class="btn btn-primary" href="{% url 'account_change_password' %}" role="button">Сменить пароль</a>
                <a id="informer" class="btn {% if object.informer.enable %}btn-danger{%else%}btn-success{%endif%}" href="{% url 'api:informer-detail' user.id %}" role="button">Информер в<span id="informer_enable">{% if not object.informer.enable %}ы{%endif%}</span>ключен</a>
                <!-- Your Stuff: Custom user template urls -->
            </div>

        </div>
        </br>
    {% else %}
        <div class="row">

            <div class="col-sm-12">
          {% if request.user|is_friends:object %}

                <a class="friends btn btn-danger" href="{% url 'friends:friends_delete' object.id %}" role="button">Удалить из друзей</a>
                
          {% else %}
            {% if request.user|request_already_exist:object %}
              <a class="friends btn btn-secondary" href="{% url 'friends:friends_request_cancel' request.user|request_friends_id:object %}" role="button">Отменить запрос в друзья</a>
            {% elif object|request_already_exist:request.user %}
            <a class="friends btn btn-success" href="{% url 'friends:friends_request_accept' object|request_friends_id:request.user %}" role="button">Добавить в друзья</a>
            <a class="friends btn btn-danger" href="{% url 'friends:friends_request_reject' object|request_friends_id:request.user %}" role="button">Отклонить запрос в друзья</a>
            {% else %}
            <a class="friends btn btn-primary" href="{% url 'friends:friends_send_request' object.id %}" role="button">Направить запрос в друзья</a>
            {% endif %}
          {% endif %}
                <!-- Your Stuff: Custom user template urls -->
            </div>

        </div>
    <!-- End Action buttons -->
    {% endif %}

</div>
{% endblock content %}

{% block page_javascript %}
  {% if object == request.user %}
    <script src="{% static 'js/informer.js' %}"></script>
  {% endif %}
    <script src="{% static 'js/friends.js' %}"></script>
    <script src="{% static 'js/toast/toast.js' %}"></script>
    <script src="{% static 'js/daterangepicker/moment.min.js' %}"></script>
    <script src="{% static 'js/daterangepicker/daterangepicker.js' %}"></script>
   <script> $(function(){
        $('#id_date').daterangepicker({
            singleDatePicker: true,
                locale: {
                    format: 'DD.MM.YYYY'
                                        }
                                    });
                });
   </script>
{% endblock page_javascript %}

bonds/templates/users/user_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}{{ user.username }}{% endblock %}

{% block content %}
  <h1>{{ user.username }}</h1>
  <form class="form-horizontal" method="post" action="{% url 'users:update' %}">
    {% csrf_token %}
    {{ form|crispy }}
    <div class="control-group">
      <div class="controls">
        <button type="submit" class="btn btn-primary">Update</button>
      </div>
    </div>
  </form>
{% endblock %}